# SwiftLint configuration for Skratch iOS app

# Directories to lint
included:
  - Skratch/
  - SkratchTests/
  - SkratchUITests/

# Directories to exclude from linting
excluded:
  - Pods/
  - DerivedData/
  - build/
  - .build/
  - Package.swift

# File extensions to lint
analyzer_rules:
  - explicit_self

# Disabled rules (customize as needed)
disabled_rules:
  - todo
  - trailing_whitespace
  - line_length

# Opt-in rules
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - legacy_random
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_type_annotation
  - strict_fileprivate
  - switch_case_alignment
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - unused_import
  - unused_private_declaration
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# Rule configurations
force_cast: warning
force_try: warning
function_body_length:
  warning: 60
  error: 100
function_parameter_count:
  warning: 5
  error: 8
identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 40
    error: 60
large_tuple:
  warning: 3
  error: 4
line_length:
  warning: 120
  error: 200
  ignores_comments: true
  ignores_urls: true
type_body_length:
  warning: 200
  error: 350
type_name:
  min_length:
    warning: 3
    error: 1
  max_length:
    warning: 40
    error: 50
variable_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 40
    error: 60

# Custom rules
custom_rules:
  # Example: Discourage force unwrapping in production code
  no_force_unwrapping_in_tests:
    name: "Force unwrapping in tests"
    regex: '!\s*\)'
    match_kinds:
      - comment
    message: "Avoid force unwrapping in test files"
    severity: warning