name: Footprint
options:
  bundleIdPrefix: com.wouterdevriendt
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
  xcodeVersion: "15.0"

schemes:
  Footprint:
    build:
      targets:
        Footprint: all
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - FootprintTests
        - FootprintUITests
    archive:
      config: Release
  FootprintUITests:
    build:
      targets:
        Footprint: all
        FootprintUITests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - FootprintUITests

settings:
  base:
    SWIFT_VERSION: "6.0"
    DEVELOPMENT_TEAM: "N324UX8D9M"

targets:
  Footprint:
    type: application
    platform: iOS
    sources:
      - Footprint
    settings:
      base:
        INFOPLIST_FILE: Footprint/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.wouterdevriendt.footprint
        CODE_SIGN_ENTITLEMENTS: Footprint/Footprint.entitlements
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        CODE_SIGN_STYLE: Automatic
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        TARGETED_DEVICE_FAMILY: "1,2"

  FootprintTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - FootprintTests
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: Footprint

  FootprintUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - FootprintUITests
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        OTHER_SWIFT_FLAGS: "-DSNAPSHOT"
    dependencies:
      - target: Footprint
