name: Footprint
options:
  bundleIdPrefix: com.wouterdevriendt
targets:
  Footprint:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Footprint
        excludes:
          - "**/*.md"
    resources:
      - path: Footprint/Assets.xcassets
      - path: Footprint/Data
      - path: Footprint/Preview\ Content
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.wouterdevriendt.footprint
      SWIFT_VERSION: 6.0
      DEVELOPMENT_TEAM: N324UX8D9M
      CODE_SIGN_STYLE: Automatic
      CODE_SIGN_ALLOW_ENTITLEMENTS_MODIFICATION: YES
      GENERATE_INFOPLIST_FILE: YES
      INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
      INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES  
      INFOPLIST_KEY_UILaunchScreen_Generation: YES
      INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
      INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
    entitlements:
      path: Footprint/Footprint.entitlements
  
  FootprintTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: FootprintTests
    settings:
      GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: Footprint
  
  FootprintUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: FootprintUITests
    settings:
      GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: Footprint
