package com.footprintmaps.android.domain.model

data class Country(
    val code: String,
    val name: String,
    val continent: Continent,
    val hasStates: Boolean = false
)

data class SubRegion(
    val code: String,
    val name: String,
    val countryCode: String = ""
)

object GeographicData {

    val countries: List<Country> = listOf(
        // Africa (54)
        Country("DZ", "Algeria", Continent.AFRICA),
        Country("AO", "Angola", Continent.AFRICA),
        Country("BJ", "Benin", Continent.AFRICA),
        Country("BW", "Botswana", Continent.AFRICA),
        Country("BF", "Burkina Faso", Continent.AFRICA),
        Country("BI", "Burundi", Continent.AFRICA),
        Country("CV", "Cabo Verde", Continent.AFRICA),
        Country("CM", "Cameroon", Continent.AFRICA),
        Country("CF", "Central African Republic", Continent.AFRICA),
        Country("TD", "Chad", Continent.AFRICA),
        Country("KM", "Comoros", Continent.AFRICA),
        Country("CG", "Congo", Continent.AFRICA),
        Country("CD", "Congo (DRC)", Continent.AFRICA),
        Country("CI", "Cote d'Ivoire", Continent.AFRICA),
        Country("DJ", "Djibouti", Continent.AFRICA),
        Country("EG", "Egypt", Continent.AFRICA),
        Country("GQ", "Equatorial Guinea", Continent.AFRICA),
        Country("ER", "Eritrea", Continent.AFRICA),
        Country("SZ", "Eswatini", Continent.AFRICA),
        Country("ET", "Ethiopia", Continent.AFRICA),
        Country("GA", "Gabon", Continent.AFRICA),
        Country("GM", "Gambia", Continent.AFRICA),
        Country("GH", "Ghana", Continent.AFRICA),
        Country("GN", "Guinea", Continent.AFRICA),
        Country("GW", "Guinea-Bissau", Continent.AFRICA),
        Country("KE", "Kenya", Continent.AFRICA),
        Country("LS", "Lesotho", Continent.AFRICA),
        Country("LR", "Liberia", Continent.AFRICA),
        Country("LY", "Libya", Continent.AFRICA),
        Country("MG", "Madagascar", Continent.AFRICA),
        Country("MW", "Malawi", Continent.AFRICA),
        Country("ML", "Mali", Continent.AFRICA),
        Country("MR", "Mauritania", Continent.AFRICA),
        Country("MU", "Mauritius", Continent.AFRICA),
        Country("MA", "Morocco", Continent.AFRICA),
        Country("MZ", "Mozambique", Continent.AFRICA),
        Country("NA", "Namibia", Continent.AFRICA),
        Country("NE", "Niger", Continent.AFRICA),
        Country("NG", "Nigeria", Continent.AFRICA),
        Country("RW", "Rwanda", Continent.AFRICA),
        Country("ST", "Sao Tome and Principe", Continent.AFRICA),
        Country("SN", "Senegal", Continent.AFRICA),
        Country("SC", "Seychelles", Continent.AFRICA),
        Country("SL", "Sierra Leone", Continent.AFRICA),
        Country("SO", "Somalia", Continent.AFRICA),
        Country("ZA", "South Africa", Continent.AFRICA),
        Country("SS", "South Sudan", Continent.AFRICA),
        Country("SD", "Sudan", Continent.AFRICA),
        Country("TZ", "Tanzania", Continent.AFRICA),
        Country("TG", "Togo", Continent.AFRICA),
        Country("TN", "Tunisia", Continent.AFRICA),
        Country("UG", "Uganda", Continent.AFRICA),
        Country("ZM", "Zambia", Continent.AFRICA),
        Country("ZW", "Zimbabwe", Continent.AFRICA),

        // Asia (49)
        Country("AF", "Afghanistan", Continent.ASIA),
        Country("AM", "Armenia", Continent.ASIA),
        Country("AZ", "Azerbaijan", Continent.ASIA),
        Country("BH", "Bahrain", Continent.ASIA),
        Country("BD", "Bangladesh", Continent.ASIA),
        Country("BT", "Bhutan", Continent.ASIA),
        Country("BN", "Brunei", Continent.ASIA),
        Country("KH", "Cambodia", Continent.ASIA),
        Country("CN", "China", Continent.ASIA),
        Country("CY", "Cyprus", Continent.ASIA),
        Country("GE", "Georgia", Continent.ASIA),
        Country("IN", "India", Continent.ASIA),
        Country("ID", "Indonesia", Continent.ASIA),
        Country("IR", "Iran", Continent.ASIA),
        Country("IQ", "Iraq", Continent.ASIA),
        Country("IL", "Israel", Continent.ASIA),
        Country("JP", "Japan", Continent.ASIA),
        Country("JO", "Jordan", Continent.ASIA),
        Country("KZ", "Kazakhstan", Continent.ASIA),
        Country("KW", "Kuwait", Continent.ASIA),
        Country("KG", "Kyrgyzstan", Continent.ASIA),
        Country("LA", "Laos", Continent.ASIA),
        Country("LB", "Lebanon", Continent.ASIA),
        Country("MY", "Malaysia", Continent.ASIA),
        Country("MV", "Maldives", Continent.ASIA),
        Country("MN", "Mongolia", Continent.ASIA),
        Country("MM", "Myanmar", Continent.ASIA),
        Country("NP", "Nepal", Continent.ASIA),
        Country("KP", "North Korea", Continent.ASIA),
        Country("OM", "Oman", Continent.ASIA),
        Country("PK", "Pakistan", Continent.ASIA),
        Country("PS", "Palestine", Continent.ASIA),
        Country("PH", "Philippines", Continent.ASIA),
        Country("QA", "Qatar", Continent.ASIA),
        Country("SA", "Saudi Arabia", Continent.ASIA),
        Country("SG", "Singapore", Continent.ASIA),
        Country("KR", "South Korea", Continent.ASIA),
        Country("LK", "Sri Lanka", Continent.ASIA),
        Country("SY", "Syria", Continent.ASIA),
        Country("TW", "Taiwan", Continent.ASIA),
        Country("TJ", "Tajikistan", Continent.ASIA),
        Country("TH", "Thailand", Continent.ASIA),
        Country("TL", "Timor-Leste", Continent.ASIA),
        Country("TR", "Turkey", Continent.ASIA),
        Country("TM", "Turkmenistan", Continent.ASIA),
        Country("AE", "United Arab Emirates", Continent.ASIA),
        Country("UZ", "Uzbekistan", Continent.ASIA),
        Country("VN", "Vietnam", Continent.ASIA),
        Country("YE", "Yemen", Continent.ASIA),

        // Europe (44)
        Country("AL", "Albania", Continent.EUROPE),
        Country("AD", "Andorra", Continent.EUROPE),
        Country("AT", "Austria", Continent.EUROPE),
        Country("BY", "Belarus", Continent.EUROPE),
        Country("BE", "Belgium", Continent.EUROPE, hasStates = true),
        Country("BA", "Bosnia and Herzegovina", Continent.EUROPE),
        Country("BG", "Bulgaria", Continent.EUROPE),
        Country("HR", "Croatia", Continent.EUROPE),
        Country("CZ", "Czech Republic", Continent.EUROPE),
        Country("DK", "Denmark", Continent.EUROPE),
        Country("EE", "Estonia", Continent.EUROPE),
        Country("FI", "Finland", Continent.EUROPE),
        Country("FR", "France", Continent.EUROPE, hasStates = true),
        Country("DE", "Germany", Continent.EUROPE, hasStates = true),
        Country("GR", "Greece", Continent.EUROPE),
        Country("HU", "Hungary", Continent.EUROPE),
        Country("IS", "Iceland", Continent.EUROPE),
        Country("IE", "Ireland", Continent.EUROPE),
        Country("IT", "Italy", Continent.EUROPE, hasStates = true),
        Country("LV", "Latvia", Continent.EUROPE),
        Country("LI", "Liechtenstein", Continent.EUROPE),
        Country("LT", "Lithuania", Continent.EUROPE),
        Country("LU", "Luxembourg", Continent.EUROPE),
        Country("MT", "Malta", Continent.EUROPE),
        Country("MD", "Moldova", Continent.EUROPE),
        Country("MC", "Monaco", Continent.EUROPE),
        Country("ME", "Montenegro", Continent.EUROPE),
        Country("NL", "Netherlands", Continent.EUROPE, hasStates = true),
        Country("MK", "North Macedonia", Continent.EUROPE),
        Country("NO", "Norway", Continent.EUROPE),
        Country("PL", "Poland", Continent.EUROPE),
        Country("PT", "Portugal", Continent.EUROPE),
        Country("RO", "Romania", Continent.EUROPE),
        Country("RU", "Russia", Continent.EUROPE, hasStates = true),
        Country("SM", "San Marino", Continent.EUROPE),
        Country("RS", "Serbia", Continent.EUROPE),
        Country("SK", "Slovakia", Continent.EUROPE),
        Country("SI", "Slovenia", Continent.EUROPE),
        Country("ES", "Spain", Continent.EUROPE, hasStates = true),
        Country("SE", "Sweden", Continent.EUROPE),
        Country("CH", "Switzerland", Continent.EUROPE),
        Country("UA", "Ukraine", Continent.EUROPE),
        Country("GB", "United Kingdom", Continent.EUROPE, hasStates = true),
        Country("VA", "Vatican City", Continent.EUROPE),

        // North America (23)
        Country("AG", "Antigua and Barbuda", Continent.NORTH_AMERICA),
        Country("BS", "Bahamas", Continent.NORTH_AMERICA),
        Country("BB", "Barbados", Continent.NORTH_AMERICA),
        Country("BZ", "Belize", Continent.NORTH_AMERICA),
        Country("CA", "Canada", Continent.NORTH_AMERICA, hasStates = true),
        Country("CR", "Costa Rica", Continent.NORTH_AMERICA),
        Country("CU", "Cuba", Continent.NORTH_AMERICA),
        Country("DM", "Dominica", Continent.NORTH_AMERICA),
        Country("DO", "Dominican Republic", Continent.NORTH_AMERICA),
        Country("SV", "El Salvador", Continent.NORTH_AMERICA),
        Country("GD", "Grenada", Continent.NORTH_AMERICA),
        Country("GT", "Guatemala", Continent.NORTH_AMERICA),
        Country("HT", "Haiti", Continent.NORTH_AMERICA),
        Country("HN", "Honduras", Continent.NORTH_AMERICA),
        Country("JM", "Jamaica", Continent.NORTH_AMERICA),
        Country("MX", "Mexico", Continent.NORTH_AMERICA, hasStates = true),
        Country("NI", "Nicaragua", Continent.NORTH_AMERICA),
        Country("PA", "Panama", Continent.NORTH_AMERICA),
        Country("KN", "Saint Kitts and Nevis", Continent.NORTH_AMERICA),
        Country("LC", "Saint Lucia", Continent.NORTH_AMERICA),
        Country("VC", "Saint Vincent and the Grenadines", Continent.NORTH_AMERICA),
        Country("TT", "Trinidad and Tobago", Continent.NORTH_AMERICA),
        Country("US", "United States", Continent.NORTH_AMERICA, hasStates = true),

        // South America (12)
        Country("AR", "Argentina", Continent.SOUTH_AMERICA, hasStates = true),
        Country("BO", "Bolivia", Continent.SOUTH_AMERICA),
        Country("BR", "Brazil", Continent.SOUTH_AMERICA, hasStates = true),
        Country("CL", "Chile", Continent.SOUTH_AMERICA),
        Country("CO", "Colombia", Continent.SOUTH_AMERICA),
        Country("EC", "Ecuador", Continent.SOUTH_AMERICA),
        Country("GY", "Guyana", Continent.SOUTH_AMERICA),
        Country("PY", "Paraguay", Continent.SOUTH_AMERICA),
        Country("PE", "Peru", Continent.SOUTH_AMERICA),
        Country("SR", "Suriname", Continent.SOUTH_AMERICA),
        Country("UY", "Uruguay", Continent.SOUTH_AMERICA),
        Country("VE", "Venezuela", Continent.SOUTH_AMERICA),

        // Oceania (14)
        Country("AU", "Australia", Continent.OCEANIA, hasStates = true),
        Country("FJ", "Fiji", Continent.OCEANIA),
        Country("KI", "Kiribati", Continent.OCEANIA),
        Country("MH", "Marshall Islands", Continent.OCEANIA),
        Country("FM", "Micronesia", Continent.OCEANIA),
        Country("NR", "Nauru", Continent.OCEANIA),
        Country("NZ", "New Zealand", Continent.OCEANIA),
        Country("PW", "Palau", Continent.OCEANIA),
        Country("PG", "Papua New Guinea", Continent.OCEANIA),
        Country("WS", "Samoa", Continent.OCEANIA),
        Country("SB", "Solomon Islands", Continent.OCEANIA),
        Country("TO", "Tonga", Continent.OCEANIA),
        Country("TV", "Tuvalu", Continent.OCEANIA),
        Country("VU", "Vanuatu", Continent.OCEANIA)
    )

    // US States (50 + DC = 51)
    val usStates: List<SubRegion> = listOf(
        SubRegion("AL", "Alabama", "US"),
        SubRegion("AK", "Alaska", "US"),
        SubRegion("AZ", "Arizona", "US"),
        SubRegion("AR", "Arkansas", "US"),
        SubRegion("CA", "California", "US"),
        SubRegion("CO", "Colorado", "US"),
        SubRegion("CT", "Connecticut", "US"),
        SubRegion("DE", "Delaware", "US"),
        SubRegion("DC", "District of Columbia", "US"),
        SubRegion("FL", "Florida", "US"),
        SubRegion("GA", "Georgia", "US"),
        SubRegion("HI", "Hawaii", "US"),
        SubRegion("ID", "Idaho", "US"),
        SubRegion("IL", "Illinois", "US"),
        SubRegion("IN", "Indiana", "US"),
        SubRegion("IA", "Iowa", "US"),
        SubRegion("KS", "Kansas", "US"),
        SubRegion("KY", "Kentucky", "US"),
        SubRegion("LA", "Louisiana", "US"),
        SubRegion("ME", "Maine", "US"),
        SubRegion("MD", "Maryland", "US"),
        SubRegion("MA", "Massachusetts", "US"),
        SubRegion("MI", "Michigan", "US"),
        SubRegion("MN", "Minnesota", "US"),
        SubRegion("MS", "Mississippi", "US"),
        SubRegion("MO", "Missouri", "US"),
        SubRegion("MT", "Montana", "US"),
        SubRegion("NE", "Nebraska", "US"),
        SubRegion("NV", "Nevada", "US"),
        SubRegion("NH", "New Hampshire", "US"),
        SubRegion("NJ", "New Jersey", "US"),
        SubRegion("NM", "New Mexico", "US"),
        SubRegion("NY", "New York", "US"),
        SubRegion("NC", "North Carolina", "US"),
        SubRegion("ND", "North Dakota", "US"),
        SubRegion("OH", "Ohio", "US"),
        SubRegion("OK", "Oklahoma", "US"),
        SubRegion("OR", "Oregon", "US"),
        SubRegion("PA", "Pennsylvania", "US"),
        SubRegion("RI", "Rhode Island", "US"),
        SubRegion("SC", "South Carolina", "US"),
        SubRegion("SD", "South Dakota", "US"),
        SubRegion("TN", "Tennessee", "US"),
        SubRegion("TX", "Texas", "US"),
        SubRegion("UT", "Utah", "US"),
        SubRegion("VT", "Vermont", "US"),
        SubRegion("VA", "Virginia", "US"),
        SubRegion("WA", "Washington", "US"),
        SubRegion("WV", "West Virginia", "US"),
        SubRegion("WI", "Wisconsin", "US"),
        SubRegion("WY", "Wyoming", "US")
    )

    // Canadian Provinces and Territories (13)
    val canadianProvinces: List<SubRegion> = listOf(
        SubRegion("AB", "Alberta", "CA"),
        SubRegion("BC", "British Columbia", "CA"),
        SubRegion("MB", "Manitoba", "CA"),
        SubRegion("NB", "New Brunswick", "CA"),
        SubRegion("NL", "Newfoundland and Labrador", "CA"),
        SubRegion("NS", "Nova Scotia", "CA"),
        SubRegion("NT", "Northwest Territories", "CA"),
        SubRegion("NU", "Nunavut", "CA"),
        SubRegion("ON", "Ontario", "CA"),
        SubRegion("PE", "Prince Edward Island", "CA"),
        SubRegion("QC", "Quebec", "CA"),
        SubRegion("SK", "Saskatchewan", "CA"),
        SubRegion("YT", "Yukon", "CA")
    )

    // Australian States and Territories (8)
    val australianStates: List<SubRegion> = listOf(
        SubRegion("ACT", "Australian Capital Territory", "AU"),
        SubRegion("NSW", "New South Wales", "AU"),
        SubRegion("NT", "Northern Territory", "AU"),
        SubRegion("QLD", "Queensland", "AU"),
        SubRegion("SA", "South Australia", "AU"),
        SubRegion("TAS", "Tasmania", "AU"),
        SubRegion("VIC", "Victoria", "AU"),
        SubRegion("WA", "Western Australia", "AU")
    )

    // Mexican States (32)
    val mexicanStates: List<SubRegion> = listOf(
        SubRegion("AGU", "Aguascalientes", "MX"),
        SubRegion("BCN", "Baja California", "MX"),
        SubRegion("BCS", "Baja California Sur", "MX"),
        SubRegion("CAM", "Campeche", "MX"),
        SubRegion("CHP", "Chiapas", "MX"),
        SubRegion("CHH", "Chihuahua", "MX"),
        SubRegion("CMX", "Ciudad de Mexico", "MX"),
        SubRegion("COA", "Coahuila", "MX"),
        SubRegion("COL", "Colima", "MX"),
        SubRegion("DUR", "Durango", "MX"),
        SubRegion("GUA", "Guanajuato", "MX"),
        SubRegion("GRO", "Guerrero", "MX"),
        SubRegion("HID", "Hidalgo", "MX"),
        SubRegion("JAL", "Jalisco", "MX"),
        SubRegion("MEX", "Mexico", "MX"),
        SubRegion("MIC", "Michoacan", "MX"),
        SubRegion("MOR", "Morelos", "MX"),
        SubRegion("NAY", "Nayarit", "MX"),
        SubRegion("NLE", "Nuevo Leon", "MX"),
        SubRegion("OAX", "Oaxaca", "MX"),
        SubRegion("PUE", "Puebla", "MX"),
        SubRegion("QUE", "Queretaro", "MX"),
        SubRegion("ROO", "Quintana Roo", "MX"),
        SubRegion("SLP", "San Luis Potosi", "MX"),
        SubRegion("SIN", "Sinaloa", "MX"),
        SubRegion("SON", "Sonora", "MX"),
        SubRegion("TAB", "Tabasco", "MX"),
        SubRegion("TAM", "Tamaulipas", "MX"),
        SubRegion("TLA", "Tlaxcala", "MX"),
        SubRegion("VER", "Veracruz", "MX"),
        SubRegion("YUC", "Yucatan", "MX"),
        SubRegion("ZAC", "Zacatecas", "MX")
    )

    // Brazilian States (27)
    val brazilianStates: List<SubRegion> = listOf(
        SubRegion("AC", "Acre", "BR"),
        SubRegion("AL", "Alagoas", "BR"),
        SubRegion("AP", "Amapa", "BR"),
        SubRegion("AM", "Amazonas", "BR"),
        SubRegion("BA", "Bahia", "BR"),
        SubRegion("CE", "Ceara", "BR"),
        SubRegion("DF", "Distrito Federal", "BR"),
        SubRegion("ES", "Espirito Santo", "BR"),
        SubRegion("GO", "Goias", "BR"),
        SubRegion("MA", "Maranhao", "BR"),
        SubRegion("MT", "Mato Grosso", "BR"),
        SubRegion("MS", "Mato Grosso do Sul", "BR"),
        SubRegion("MG", "Minas Gerais", "BR"),
        SubRegion("PA", "Para", "BR"),
        SubRegion("PB", "Paraiba", "BR"),
        SubRegion("PR", "Parana", "BR"),
        SubRegion("PE", "Pernambuco", "BR"),
        SubRegion("PI", "Piaui", "BR"),
        SubRegion("RJ", "Rio de Janeiro", "BR"),
        SubRegion("RN", "Rio Grande do Norte", "BR"),
        SubRegion("RS", "Rio Grande do Sul", "BR"),
        SubRegion("RO", "Rondonia", "BR"),
        SubRegion("RR", "Roraima", "BR"),
        SubRegion("SC", "Santa Catarina", "BR"),
        SubRegion("SP", "Sao Paulo", "BR"),
        SubRegion("SE", "Sergipe", "BR"),
        SubRegion("TO", "Tocantins", "BR")
    )

    // German States (16)
    val germanStates: List<SubRegion> = listOf(
        SubRegion("BW", "Baden-Wurttemberg", "DE"),
        SubRegion("BY", "Bavaria", "DE"),
        SubRegion("BE", "Berlin", "DE"),
        SubRegion("BB", "Brandenburg", "DE"),
        SubRegion("HB", "Bremen", "DE"),
        SubRegion("HH", "Hamburg", "DE"),
        SubRegion("HE", "Hesse", "DE"),
        SubRegion("MV", "Mecklenburg-Vorpommern", "DE"),
        SubRegion("NI", "Lower Saxony", "DE"),
        SubRegion("NW", "North Rhine-Westphalia", "DE"),
        SubRegion("RP", "Rhineland-Palatinate", "DE"),
        SubRegion("SL", "Saarland", "DE"),
        SubRegion("SN", "Saxony", "DE"),
        SubRegion("ST", "Saxony-Anhalt", "DE"),
        SubRegion("SH", "Schleswig-Holstein", "DE"),
        SubRegion("TH", "Thuringia", "DE")
    )

    // French Departments (101)
    val frenchDepartments: List<SubRegion> = listOf(
        SubRegion("01", "Ain", "FR"),
        SubRegion("02", "Aisne", "FR"),
        SubRegion("03", "Allier", "FR"),
        SubRegion("04", "Alpes-de-Haute-Provence", "FR"),
        SubRegion("05", "Hautes-Alpes", "FR"),
        SubRegion("06", "Alpes-Maritimes", "FR"),
        SubRegion("07", "Ardeche", "FR"),
        SubRegion("08", "Ardennes", "FR"),
        SubRegion("09", "Ariege", "FR"),
        SubRegion("10", "Aube", "FR"),
        SubRegion("11", "Aude", "FR"),
        SubRegion("12", "Aveyron", "FR"),
        SubRegion("13", "Bouches-du-Rhone", "FR"),
        SubRegion("14", "Calvados", "FR"),
        SubRegion("15", "Cantal", "FR"),
        SubRegion("16", "Charente", "FR"),
        SubRegion("17", "Charente-Maritime", "FR"),
        SubRegion("18", "Cher", "FR"),
        SubRegion("19", "Correze", "FR"),
        SubRegion("21", "Cote-d'Or", "FR"),
        SubRegion("22", "Cotes-d'Armor", "FR"),
        SubRegion("23", "Creuse", "FR"),
        SubRegion("24", "Dordogne", "FR"),
        SubRegion("25", "Doubs", "FR"),
        SubRegion("26", "Drome", "FR"),
        SubRegion("27", "Eure", "FR"),
        SubRegion("28", "Eure-et-Loir", "FR"),
        SubRegion("29", "Finistere", "FR"),
        SubRegion("2A", "Corse-du-Sud", "FR"),
        SubRegion("2B", "Haute-Corse", "FR"),
        SubRegion("30", "Gard", "FR"),
        SubRegion("31", "Haute-Garonne", "FR"),
        SubRegion("32", "Gers", "FR"),
        SubRegion("33", "Gironde", "FR"),
        SubRegion("34", "Herault", "FR"),
        SubRegion("35", "Ille-et-Vilaine", "FR"),
        SubRegion("36", "Indre", "FR"),
        SubRegion("37", "Indre-et-Loire", "FR"),
        SubRegion("38", "Isere", "FR"),
        SubRegion("39", "Jura", "FR"),
        SubRegion("40", "Landes", "FR"),
        SubRegion("41", "Loir-et-Cher", "FR"),
        SubRegion("42", "Loire", "FR"),
        SubRegion("43", "Haute-Loire", "FR"),
        SubRegion("44", "Loire-Atlantique", "FR"),
        SubRegion("45", "Loiret", "FR"),
        SubRegion("46", "Lot", "FR"),
        SubRegion("47", "Lot-et-Garonne", "FR"),
        SubRegion("48", "Lozere", "FR"),
        SubRegion("49", "Maine-et-Loire", "FR"),
        SubRegion("50", "Manche", "FR"),
        SubRegion("51", "Marne", "FR"),
        SubRegion("52", "Haute-Marne", "FR"),
        SubRegion("53", "Mayenne", "FR"),
        SubRegion("54", "Meurthe-et-Moselle", "FR"),
        SubRegion("55", "Meuse", "FR"),
        SubRegion("56", "Morbihan", "FR"),
        SubRegion("57", "Moselle", "FR"),
        SubRegion("58", "Nievre", "FR"),
        SubRegion("59", "Nord", "FR"),
        SubRegion("60", "Oise", "FR"),
        SubRegion("61", "Orne", "FR"),
        SubRegion("62", "Pas-de-Calais", "FR"),
        SubRegion("63", "Puy-de-Dome", "FR"),
        SubRegion("64", "Pyrenees-Atlantiques", "FR"),
        SubRegion("65", "Hautes-Pyrenees", "FR"),
        SubRegion("66", "Pyrenees-Orientales", "FR"),
        SubRegion("67", "Bas-Rhin", "FR"),
        SubRegion("68", "Haut-Rhin", "FR"),
        SubRegion("69", "Rhone", "FR"),
        SubRegion("70", "Haute-Saone", "FR"),
        SubRegion("71", "Saone-et-Loire", "FR"),
        SubRegion("72", "Sarthe", "FR"),
        SubRegion("73", "Savoie", "FR"),
        SubRegion("74", "Haute-Savoie", "FR"),
        SubRegion("75", "Paris", "FR"),
        SubRegion("76", "Seine-Maritime", "FR"),
        SubRegion("77", "Seine-et-Marne", "FR"),
        SubRegion("78", "Yvelines", "FR"),
        SubRegion("79", "Deux-Sevres", "FR"),
        SubRegion("80", "Somme", "FR"),
        SubRegion("81", "Tarn", "FR"),
        SubRegion("82", "Tarn-et-Garonne", "FR"),
        SubRegion("83", "Var", "FR"),
        SubRegion("84", "Vaucluse", "FR"),
        SubRegion("85", "Vendee", "FR"),
        SubRegion("86", "Vienne", "FR"),
        SubRegion("87", "Haute-Vienne", "FR"),
        SubRegion("88", "Vosges", "FR"),
        SubRegion("89", "Yonne", "FR"),
        SubRegion("90", "Territoire de Belfort", "FR"),
        SubRegion("91", "Essonne", "FR"),
        SubRegion("92", "Hauts-de-Seine", "FR"),
        SubRegion("93", "Seine-Saint-Denis", "FR"),
        SubRegion("94", "Val-de-Marne", "FR"),
        SubRegion("95", "Val-d'Oise", "FR"),
        // Overseas departments
        SubRegion("GF", "Guyane francaise", "FR"),
        SubRegion("GP", "Guadeloupe", "FR"),
        SubRegion("MQ", "Martinique", "FR"),
        SubRegion("RE", "La Reunion", "FR"),
        SubRegion("YT", "Mayotte", "FR")
    )

    // Spanish Autonomous Communities (19)
    val spanishCommunities: List<SubRegion> = listOf(
        SubRegion("AN", "Andalusia", "ES"),
        SubRegion("AR", "Aragon", "ES"),
        SubRegion("AS", "Asturias", "ES"),
        SubRegion("IB", "Balearic Islands", "ES"),
        SubRegion("PV", "Basque Country", "ES"),
        SubRegion("CN", "Canary Islands", "ES"),
        SubRegion("CB", "Cantabria", "ES"),
        SubRegion("CL", "Castile and Leon", "ES"),
        SubRegion("CM", "Castilla-La Mancha", "ES"),
        SubRegion("CT", "Catalonia", "ES"),
        SubRegion("CE", "Ceuta", "ES"),
        SubRegion("EX", "Extremadura", "ES"),
        SubRegion("GA", "Galicia", "ES"),
        SubRegion("RI", "La Rioja", "ES"),
        SubRegion("MD", "Madrid", "ES"),
        SubRegion("ML", "Melilla", "ES"),
        SubRegion("MC", "Murcia", "ES"),
        SubRegion("NC", "Navarre", "ES"),
        SubRegion("VC", "Valencia", "ES")
    )

    // Italian Provinces (110)
    val italianProvinces: List<SubRegion> = listOf(
        SubRegion("AG", "Agrigento", "IT"), SubRegion("AL", "Alessandria", "IT"),
        SubRegion("AN", "Ancona", "IT"), SubRegion("AO", "Aosta", "IT"),
        SubRegion("AR", "Arezzo", "IT"), SubRegion("AP", "Ascoli Piceno", "IT"),
        SubRegion("AT", "Asti", "IT"), SubRegion("AV", "Avellino", "IT"),
        SubRegion("BA", "Bari", "IT"), SubRegion("BT", "Barletta-Andria-Trani", "IT"),
        SubRegion("BL", "Belluno", "IT"), SubRegion("BN", "Benevento", "IT"),
        SubRegion("BG", "Bergamo", "IT"), SubRegion("BI", "Biella", "IT"),
        SubRegion("BO", "Bologna", "IT"), SubRegion("BZ", "Bolzano", "IT"),
        SubRegion("BS", "Brescia", "IT"), SubRegion("BR", "Brindisi", "IT"),
        SubRegion("CA", "Cagliari", "IT"), SubRegion("CL", "Caltanissetta", "IT"),
        SubRegion("CB", "Campobasso", "IT"), SubRegion("CI", "Carbonia-Iglesias", "IT"),
        SubRegion("CE", "Caserta", "IT"), SubRegion("CT", "Catania", "IT"),
        SubRegion("CZ", "Catanzaro", "IT"), SubRegion("CH", "Chieti", "IT"),
        SubRegion("CO", "Como", "IT"), SubRegion("CS", "Cosenza", "IT"),
        SubRegion("CR", "Cremona", "IT"), SubRegion("KR", "Crotone", "IT"),
        SubRegion("CN", "Cuneo", "IT"), SubRegion("EN", "Enna", "IT"),
        SubRegion("FM", "Fermo", "IT"), SubRegion("FE", "Ferrara", "IT"),
        SubRegion("FI", "Firenze", "IT"), SubRegion("FG", "Foggia", "IT"),
        SubRegion("FC", "Forli-Cesena", "IT"), SubRegion("FR", "Frosinone", "IT"),
        SubRegion("GE", "Genova", "IT"), SubRegion("GO", "Gorizia", "IT"),
        SubRegion("GR", "Grosseto", "IT"), SubRegion("IM", "Imperia", "IT"),
        SubRegion("IS", "Isernia", "IT"), SubRegion("AQ", "L'Aquila", "IT"),
        SubRegion("SP", "La Spezia", "IT"), SubRegion("LT", "Latina", "IT"),
        SubRegion("LE", "Lecce", "IT"), SubRegion("LC", "Lecco", "IT"),
        SubRegion("LI", "Livorno", "IT"), SubRegion("LO", "Lodi", "IT"),
        SubRegion("LU", "Lucca", "IT"), SubRegion("MC", "Macerata", "IT"),
        SubRegion("MN", "Mantova", "IT"), SubRegion("MS", "Massa-Carrara", "IT"),
        SubRegion("MT", "Matera", "IT"), SubRegion("VS", "Medio Campidano", "IT"),
        SubRegion("ME", "Messina", "IT"), SubRegion("MI", "Milano", "IT"),
        SubRegion("MO", "Modena", "IT"), SubRegion("MB", "Monza e Brianza", "IT"),
        SubRegion("NA", "Napoli", "IT"), SubRegion("NO", "Novara", "IT"),
        SubRegion("NU", "Nuoro", "IT"), SubRegion("OG", "Ogliastra", "IT"),
        SubRegion("OT", "Olbia-Tempio", "IT"), SubRegion("OR", "Oristano", "IT"),
        SubRegion("PD", "Padova", "IT"), SubRegion("PA", "Palermo", "IT"),
        SubRegion("PR", "Parma", "IT"), SubRegion("PV", "Pavia", "IT"),
        SubRegion("PG", "Perugia", "IT"), SubRegion("PU", "Pesaro e Urbino", "IT"),
        SubRegion("PE", "Pescara", "IT"), SubRegion("PC", "Piacenza", "IT"),
        SubRegion("PI", "Pisa", "IT"), SubRegion("PT", "Pistoia", "IT"),
        SubRegion("PN", "Pordenone", "IT"), SubRegion("PZ", "Potenza", "IT"),
        SubRegion("PO", "Prato", "IT"), SubRegion("RG", "Ragusa", "IT"),
        SubRegion("RA", "Ravenna", "IT"), SubRegion("RC", "Reggio Calabria", "IT"),
        SubRegion("RE", "Reggio Emilia", "IT"), SubRegion("RI", "Rieti", "IT"),
        SubRegion("RN", "Rimini", "IT"), SubRegion("RM", "Roma", "IT"),
        SubRegion("RO", "Rovigo", "IT"), SubRegion("SA", "Salerno", "IT"),
        SubRegion("SS", "Sassari", "IT"), SubRegion("SV", "Savona", "IT"),
        SubRegion("SI", "Siena", "IT"), SubRegion("SR", "Siracusa", "IT"),
        SubRegion("SO", "Sondrio", "IT"), SubRegion("TA", "Taranto", "IT"),
        SubRegion("TE", "Teramo", "IT"), SubRegion("TR", "Terni", "IT"),
        SubRegion("TP", "Trapani", "IT"), SubRegion("TN", "Trento", "IT"),
        SubRegion("TV", "Treviso", "IT"), SubRegion("TS", "Trieste", "IT"),
        SubRegion("TO", "Torino", "IT"), SubRegion("UD", "Udine", "IT"),
        SubRegion("VA", "Varese", "IT"), SubRegion("VE", "Venezia", "IT"),
        SubRegion("VB", "Verbano-Cusio-Ossola", "IT"), SubRegion("VC", "Vercelli", "IT"),
        SubRegion("VR", "Verona", "IT"), SubRegion("VV", "Vibo Valentia", "IT"),
        SubRegion("VI", "Vicenza", "IT"), SubRegion("VT", "Viterbo", "IT")
    )

    // Dutch Provinces (12)
    val dutchProvinces: List<SubRegion> = listOf(
        SubRegion("DR", "Drenthe", "NL"),
        SubRegion("FL", "Flevoland", "NL"),
        SubRegion("FR", "Friesland", "NL"),
        SubRegion("GE", "Gelderland", "NL"),
        SubRegion("GR", "Groningen", "NL"),
        SubRegion("LI", "Limburg", "NL"),
        SubRegion("NB", "North Brabant", "NL"),
        SubRegion("NH", "North Holland", "NL"),
        SubRegion("OV", "Overijssel", "NL"),
        SubRegion("UT", "Utrecht", "NL"),
        SubRegion("ZE", "Zeeland", "NL"),
        SubRegion("ZH", "South Holland", "NL")
    )

    // Belgian Provinces (11)
    val belgianProvinces: List<SubRegion> = listOf(
        SubRegion("VAN", "Antwerp", "BE"),
        SubRegion("BRU", "Brussels Capital Region", "BE"),
        SubRegion("VOV", "East Flanders", "BE"),
        SubRegion("VBR", "Flemish Brabant", "BE"),
        SubRegion("WHT", "Hainaut", "BE"),
        SubRegion("WLG", "Liege", "BE"),
        SubRegion("VLI", "Limburg", "BE"),
        SubRegion("WLX", "Luxembourg", "BE"),
        SubRegion("WNA", "Namur", "BE"),
        SubRegion("WBR", "Walloon Brabant", "BE"),
        SubRegion("VWV", "West Flanders", "BE")
    )

    // UK Council Areas (217) - matching iOS exactly
    val ukCouncilAreas: List<SubRegion> = listOf(
        SubRegion("ABE", "Aberdeen", "GB"), SubRegion("ABD", "Aberdeenshire", "GB"),
        SubRegion("AGY", "Anglesey", "GB"), SubRegion("ANS", "Angus", "GB"),
        SubRegion("ANT", "Antrim", "GB"), SubRegion("ARD", "Ards", "GB"),
        SubRegion("AGB", "Argyll and Bute", "GB"), SubRegion("ARM", "Armagh", "GB"),
        SubRegion("BLA", "Ballymena", "GB"), SubRegion("BLY", "Ballymoney", "GB"),
        SubRegion("BNB", "Banbridge", "GB"), SubRegion("BDG", "Barking and Dagenham", "GB"),
        SubRegion("BNE", "Barnet", "GB"), SubRegion("BNS", "Barnsley", "GB"),
        SubRegion("BAS", "Bath and North East Somerset", "GB"), SubRegion("BDF", "Bedford", "GB"),
        SubRegion("BFS", "Belfast", "GB"), SubRegion("BEX", "Bexley", "GB"),
        SubRegion("BIR", "Birmingham", "GB"), SubRegion("BBD", "Blackburn with Darwen", "GB"),
        SubRegion("BPL", "Blackpool", "GB"), SubRegion("BGW", "Blaenau Gwent", "GB"),
        SubRegion("BOL", "Bolton", "GB"), SubRegion("BMH", "Bournemouth", "GB"),
        SubRegion("BRC", "Bracknell Forest", "GB"), SubRegion("BRD", "Bradford", "GB"),
        SubRegion("BEN", "Brent", "GB"), SubRegion("BGE", "Bridgend", "GB"),
        SubRegion("BNH", "Brighton and Hove", "GB"), SubRegion("BST", "Bristol", "GB"),
        SubRegion("BRY", "Bromley", "GB"), SubRegion("BKM", "Buckinghamshire", "GB"),
        SubRegion("BUR", "Bury", "GB"), SubRegion("CAY", "Caerphilly", "GB"),
        SubRegion("CLD", "Calderdale", "GB"), SubRegion("CAM", "Cambridgeshire", "GB"),
        SubRegion("CMD", "Camden", "GB"), SubRegion("CRF", "Cardiff", "GB"),
        SubRegion("CMN", "Carmarthenshire", "GB"), SubRegion("CKF", "Carrickfergus", "GB"),
        SubRegion("CSR", "Castlereagh", "GB"), SubRegion("CBF", "Central Bedfordshire", "GB"),
        SubRegion("CGN", "Ceredigion", "GB"), SubRegion("CHE", "Cheshire East", "GB"),
        SubRegion("CHW", "Cheshire West and Chester", "GB"), SubRegion("LND", "City of London", "GB"),
        SubRegion("CLK", "Clackmannanshire", "GB"), SubRegion("CLR", "Coleraine", "GB"),
        SubRegion("CWY", "Conwy", "GB"), SubRegion("CON", "Cornwall", "GB"),
        SubRegion("COV", "Coventry", "GB"), SubRegion("CGV", "Craigavon", "GB"),
        SubRegion("CRY", "Croydon", "GB"), SubRegion("CMA", "Cumbria", "GB"),
        SubRegion("DAL", "Darlington", "GB"), SubRegion("DEN", "Denbighshire", "GB"),
        SubRegion("DER", "Derby", "GB"), SubRegion("DBY", "Derbyshire", "GB"),
        SubRegion("DRY", "Derry", "GB"), SubRegion("DEV", "Devon", "GB"),
        SubRegion("DNC", "Doncaster", "GB"), SubRegion("DOR", "Dorset", "GB"),
        SubRegion("DOW", "Down", "GB"), SubRegion("DUD", "Dudley", "GB"),
        SubRegion("DGY", "Dumfries and Galloway", "GB"), SubRegion("DND", "Dundee", "GB"),
        SubRegion("DGN", "Dungannon", "GB"), SubRegion("DUR", "Durham", "GB"),
        SubRegion("EAL", "Ealing", "GB"), SubRegion("EAY", "East Ayrshire", "GB"),
        SubRegion("EDU", "East Dunbartonshire", "GB"), SubRegion("ELN", "East Lothian", "GB"),
        SubRegion("ERW", "East Renfrewshire", "GB"), SubRegion("ERY", "East Riding of Yorkshire", "GB"),
        SubRegion("ESX", "East Sussex", "GB"), SubRegion("EDH", "Edinburgh", "GB"),
        SubRegion("ELS", "Eilean Siar", "GB"), SubRegion("ENF", "Enfield", "GB"),
        SubRegion("ESS", "Essex", "GB"), SubRegion("FAL", "Falkirk", "GB"),
        SubRegion("FER", "Fermanagh", "GB"), SubRegion("FIF", "Fife", "GB"),
        SubRegion("FLN", "Flintshire", "GB"), SubRegion("GAT", "Gateshead", "GB"),
        SubRegion("GLG", "Glasgow", "GB"), SubRegion("GLS", "Gloucestershire", "GB"),
        SubRegion("GRE", "Greenwich", "GB"), SubRegion("GWN", "Gwynedd", "GB"),
        SubRegion("HCK", "Hackney", "GB"), SubRegion("HAL", "Halton", "GB"),
        SubRegion("HMF", "Hammersmith and Fulham", "GB"), SubRegion("HAM", "Hampshire", "GB"),
        SubRegion("HRY", "Haringey", "GB"), SubRegion("HRW", "Harrow", "GB"),
        SubRegion("HPL", "Hartlepool", "GB"), SubRegion("HAV", "Havering", "GB"),
        SubRegion("HEF", "Herefordshire", "GB"), SubRegion("HRT", "Hertfordshire", "GB"),
        SubRegion("HLD", "Highland", "GB"), SubRegion("HIL", "Hillingdon", "GB"),
        SubRegion("HNS", "Hounslow", "GB"), SubRegion("IVC", "Inverclyde", "GB"),
        SubRegion("IOW", "Isle of Wight", "GB"), SubRegion("IOS", "Isles of Scilly", "GB"),
        SubRegion("ISL", "Islington", "GB"), SubRegion("KEC", "Kensington and Chelsea", "GB"),
        SubRegion("KEN", "Kent", "GB"), SubRegion("KHL", "Kingston upon Hull", "GB"),
        SubRegion("KTT", "Kingston upon Thames", "GB"), SubRegion("KIR", "Kirklees", "GB"),
        SubRegion("KWL", "Knowsley", "GB"), SubRegion("LBH", "Lambeth", "GB"),
        SubRegion("LAN", "Lancashire", "GB"), SubRegion("LRN", "Larne", "GB"),
        SubRegion("LDS", "Leeds", "GB"), SubRegion("LCE", "Leicester", "GB"),
        SubRegion("LEC", "Leicestershire", "GB"), SubRegion("LEW", "Lewisham", "GB"),
        SubRegion("LMV", "Limavady", "GB"), SubRegion("LIN", "Lincolnshire", "GB"),
        SubRegion("LSB", "Lisburn", "GB"), SubRegion("LIV", "Liverpool", "GB"),
        SubRegion("LUT", "Luton", "GB"), SubRegion("MFT", "Magherafelt", "GB"),
        SubRegion("MAN", "Manchester", "GB"), SubRegion("MDW", "Medway", "GB"),
        SubRegion("MTY", "Merthyr Tydfil", "GB"), SubRegion("MRT", "Merton", "GB"),
        SubRegion("MDB", "Middlesbrough", "GB"), SubRegion("MLN", "Midlothian", "GB"),
        SubRegion("MIK", "Milton Keynes", "GB"), SubRegion("MON", "Monmouthshire", "GB"),
        SubRegion("MRY", "Moray", "GB"), SubRegion("MYL", "Moyle", "GB"),
        SubRegion("NTL", "Neath Port Talbot", "GB"), SubRegion("NET", "Newcastle upon Tyne", "GB"),
        SubRegion("NWM", "Newham", "GB"), SubRegion("NWP", "Newport", "GB"),
        SubRegion("NYM", "Newry and Mourne", "GB"), SubRegion("NTA", "Newtownabbey", "GB"),
        SubRegion("NFK", "Norfolk", "GB"), SubRegion("NAY", "North Ayrshire", "GB"),
        SubRegion("NDN", "North Down", "GB"), SubRegion("NEL", "North East Lincolnshire", "GB"),
        SubRegion("NLK", "North Lanarkshire", "GB"), SubRegion("NLN", "North Lincolnshire", "GB"),
        SubRegion("NSM", "North Somerset", "GB"), SubRegion("NTY", "North Tyneside", "GB"),
        SubRegion("NYK", "North Yorkshire", "GB"), SubRegion("NTH", "Northamptonshire", "GB"),
        SubRegion("NBL", "Northumberland", "GB"), SubRegion("NGM", "Nottingham", "GB"),
        SubRegion("NTT", "Nottinghamshire", "GB"), SubRegion("OLD", "Oldham", "GB"),
        SubRegion("OMH", "Omagh", "GB"), SubRegion("ORK", "Orkney", "GB"),
        SubRegion("OXF", "Oxfordshire", "GB"), SubRegion("PEM", "Pembrokeshire", "GB"),
        SubRegion("PKN", "Perth and Kinross", "GB"), SubRegion("PTE", "Peterborough", "GB"),
        SubRegion("PLY", "Plymouth", "GB"), SubRegion("POL", "Poole", "GB"),
        SubRegion("POR", "Portsmouth", "GB"), SubRegion("POW", "Powys", "GB"),
        SubRegion("RDG", "Reading", "GB"), SubRegion("RDB", "Redbridge", "GB"),
        SubRegion("RCC", "Redcar and Cleveland", "GB"), SubRegion("RFW", "Renfrewshire", "GB"),
        SubRegion("RCT", "Rhondda Cynon Taf", "GB"), SubRegion("RIC", "Richmond upon Thames", "GB"),
        SubRegion("RCH", "Rochdale", "GB"), SubRegion("ROT", "Rotherham", "GB"),
        SubRegion("RUT", "Rutland", "GB"), SubRegion("SLF", "Salford", "GB"),
        SubRegion("SAW", "Sandwell", "GB"), SubRegion("SCB", "Scottish Borders", "GB"),
        SubRegion("SFT", "Sefton", "GB"), SubRegion("SHF", "Sheffield", "GB"),
        SubRegion("ZET", "Shetland Islands", "GB"), SubRegion("SHR", "Shropshire", "GB"),
        SubRegion("SLG", "Slough", "GB"), SubRegion("SOL", "Solihull", "GB"),
        SubRegion("SOM", "Somerset", "GB"), SubRegion("SAY", "South Ayrshire", "GB"),
        SubRegion("SGC", "South Gloucestershire", "GB"), SubRegion("SLK", "South Lanarkshire", "GB"),
        SubRegion("STY", "South Tyneside", "GB"), SubRegion("STH", "Southampton", "GB"),
        SubRegion("SOS", "Southend-on-Sea", "GB"), SubRegion("SWK", "Southwark", "GB"),
        SubRegion("STS", "Staffordshire", "GB"), SubRegion("STG", "Stirling", "GB"),
        SubRegion("SKP", "Stockport", "GB"), SubRegion("STT", "Stockton-on-Tees", "GB"),
        SubRegion("STE", "Stoke-on-Trent", "GB"), SubRegion("STB", "Strabane", "GB"),
        SubRegion("SFK", "Suffolk", "GB"), SubRegion("SND", "Sunderland", "GB"),
        SubRegion("SRY", "Surrey", "GB"), SubRegion("STN", "Sutton", "GB"),
        SubRegion("SWA", "Swansea", "GB"), SubRegion("SWD", "Swindon", "GB"),
        SubRegion("TAM", "Tameside", "GB"), SubRegion("TFW", "Telford and Wrekin", "GB"),
        SubRegion("THR", "Thurrock", "GB"), SubRegion("TOB", "Torbay", "GB"),
        SubRegion("TOF", "Torfaen", "GB"), SubRegion("TWH", "Tower Hamlets", "GB"),
        SubRegion("TRF", "Trafford", "GB"), SubRegion("VGL", "Vale of Glamorgan", "GB"),
        SubRegion("WKF", "Wakefield", "GB"), SubRegion("WLL", "Walsall", "GB"),
        SubRegion("WFT", "Waltham Forest", "GB"), SubRegion("WND", "Wandsworth", "GB"),
        SubRegion("WRT", "Warrington", "GB"), SubRegion("WAR", "Warwickshire", "GB"),
        SubRegion("WBK", "West Berkshire", "GB"), SubRegion("WDU", "West Dunbartonshire", "GB"),
        SubRegion("WLN", "West Lothian", "GB"), SubRegion("WSX", "West Sussex", "GB"),
        SubRegion("WSM", "Westminster", "GB"), SubRegion("WGN", "Wigan", "GB"),
        SubRegion("WIL", "Wiltshire", "GB"), SubRegion("WNM", "Windsor and Maidenhead", "GB"),
        SubRegion("WOK", "Wokingham", "GB"), SubRegion("WLV", "Wolverhampton", "GB"),
        SubRegion("WOR", "Worcestershire", "GB"), SubRegion("WRX", "Wrexham", "GB"),
        SubRegion("YOR", "York", "GB")
    )

    // Russian Federal Subjects (85)
    val russianFederalSubjects: List<SubRegion> = listOf(
        // Republics
        SubRegion("AD", "Adygea", "RU"), SubRegion("AL", "Altai Republic", "RU"),
        SubRegion("BA", "Bashkortostan", "RU"), SubRegion("BU", "Buryatia", "RU"),
        SubRegion("CE", "Chechnya", "RU"), SubRegion("CU", "Chuvashia", "RU"),
        SubRegion("DA", "Dagestan", "RU"), SubRegion("IN", "Ingushetia", "RU"),
        SubRegion("KB", "Kabardino-Balkaria", "RU"), SubRegion("KL", "Kalmykia", "RU"),
        SubRegion("KC", "Karachay-Cherkessia", "RU"), SubRegion("KR", "Karelia", "RU"),
        SubRegion("KK", "Khakassia", "RU"), SubRegion("KO", "Komi", "RU"),
        SubRegion("ME", "Mari El", "RU"), SubRegion("MO", "Mordovia", "RU"),
        SubRegion("SE", "North Ossetia-Alania", "RU"), SubRegion("SA", "Sakha (Yakutia)", "RU"),
        SubRegion("TA", "Tatarstan", "RU"), SubRegion("TY", "Tuva", "RU"),
        SubRegion("UD", "Udmurtia", "RU"),
        // Federal cities
        SubRegion("MOW", "Moscow", "RU"), SubRegion("SPE", "Saint Petersburg", "RU"),
        SubRegion("SEV", "Sevastopol", "RU"),
        // Krais
        SubRegion("ALT", "Altai Krai", "RU"), SubRegion("KAM", "Kamchatka Krai", "RU"),
        SubRegion("KHA", "Khabarovsk Krai", "RU"), SubRegion("KDA", "Krasnodar Krai", "RU"),
        SubRegion("KYA", "Krasnoyarsk Krai", "RU"), SubRegion("PER", "Perm Krai", "RU"),
        SubRegion("PRI", "Primorsky Krai", "RU"), SubRegion("STA", "Stavropol Krai", "RU"),
        SubRegion("ZAB", "Zabaykalsky Krai", "RU"),
        // Oblasts
        SubRegion("AMU", "Amur Oblast", "RU"), SubRegion("ARK", "Arkhangelsk Oblast", "RU"),
        SubRegion("AST", "Astrakhan Oblast", "RU"), SubRegion("BEL", "Belgorod Oblast", "RU"),
        SubRegion("BRY", "Bryansk Oblast", "RU"), SubRegion("CHE", "Chelyabinsk Oblast", "RU"),
        SubRegion("IRK", "Irkutsk Oblast", "RU"), SubRegion("IVA", "Ivanovo Oblast", "RU"),
        SubRegion("KGD", "Kaliningrad Oblast", "RU"), SubRegion("KLU", "Kaluga Oblast", "RU"),
        SubRegion("KEM", "Kemerovo Oblast", "RU"), SubRegion("KIR", "Kirov Oblast", "RU"),
        SubRegion("KOS", "Kostroma Oblast", "RU"), SubRegion("KGN", "Kurgan Oblast", "RU"),
        SubRegion("KRS", "Kursk Oblast", "RU"), SubRegion("LEN", "Leningrad Oblast", "RU"),
        SubRegion("LIP", "Lipetsk Oblast", "RU"), SubRegion("MAG", "Magadan Oblast", "RU"),
        SubRegion("MOS", "Moscow Oblast", "RU"), SubRegion("MUR", "Murmansk Oblast", "RU"),
        SubRegion("NIZ", "Nizhny Novgorod Oblast", "RU"), SubRegion("NGR", "Novgorod Oblast", "RU"),
        SubRegion("NVS", "Novosibirsk Oblast", "RU"), SubRegion("OMS", "Omsk Oblast", "RU"),
        SubRegion("ORE", "Orenburg Oblast", "RU"), SubRegion("ORL", "Oryol Oblast", "RU"),
        SubRegion("PNZ", "Penza Oblast", "RU"), SubRegion("PSK", "Pskov Oblast", "RU"),
        SubRegion("ROS", "Rostov Oblast", "RU"), SubRegion("RYA", "Ryazan Oblast", "RU"),
        SubRegion("SAK", "Sakhalin Oblast", "RU"), SubRegion("SAM", "Samara Oblast", "RU"),
        SubRegion("SAR", "Saratov Oblast", "RU"), SubRegion("SMO", "Smolensk Oblast", "RU"),
        SubRegion("SVE", "Sverdlovsk Oblast", "RU"), SubRegion("TAM", "Tambov Oblast", "RU"),
        SubRegion("TOM", "Tomsk Oblast", "RU"), SubRegion("TUL", "Tula Oblast", "RU"),
        SubRegion("TVE", "Tver Oblast", "RU"), SubRegion("TYU", "Tyumen Oblast", "RU"),
        SubRegion("ULY", "Ulyanovsk Oblast", "RU"), SubRegion("VLA", "Vladimir Oblast", "RU"),
        SubRegion("VGG", "Volgograd Oblast", "RU"), SubRegion("VLG", "Vologda Oblast", "RU"),
        SubRegion("VOR", "Voronezh Oblast", "RU"), SubRegion("YAR", "Yaroslavl Oblast", "RU"),
        // Autonomous Okrugs
        SubRegion("CHU", "Chukotka Autonomous Okrug", "RU"),
        SubRegion("KHM", "Khanty-Mansi Autonomous Okrug", "RU"),
        SubRegion("NEN", "Nenets Autonomous Okrug", "RU"),
        SubRegion("YAN", "Yamalo-Nenets Autonomous Okrug", "RU"),
        // Autonomous Oblast
        SubRegion("YEV", "Jewish Autonomous Oblast", "RU")
    )

    // Argentine Provinces (24)
    val argentineProvinces: List<SubRegion> = listOf(
        SubRegion("C", "Buenos Aires City", "AR"),
        SubRegion("B", "Buenos Aires Province", "AR"),
        SubRegion("K", "Catamarca", "AR"),
        SubRegion("H", "Chaco", "AR"),
        SubRegion("U", "Chubut", "AR"),
        SubRegion("X", "Cordoba", "AR"),
        SubRegion("W", "Corrientes", "AR"),
        SubRegion("E", "Entre Rios", "AR"),
        SubRegion("P", "Formosa", "AR"),
        SubRegion("Y", "Jujuy", "AR"),
        SubRegion("L", "La Pampa", "AR"),
        SubRegion("F", "La Rioja", "AR"),
        SubRegion("M", "Mendoza", "AR"),
        SubRegion("N", "Misiones", "AR"),
        SubRegion("Q", "Neuquen", "AR"),
        SubRegion("R", "Rio Negro", "AR"),
        SubRegion("A", "Salta", "AR"),
        SubRegion("J", "San Juan", "AR"),
        SubRegion("D", "San Luis", "AR"),
        SubRegion("Z", "Santa Cruz", "AR"),
        SubRegion("S", "Santa Fe", "AR"),
        SubRegion("G", "Santiago del Estero", "AR"),
        SubRegion("V", "Tierra del Fuego", "AR"),
        SubRegion("T", "Tucuman", "AR")
    )

    val countriesByContinent: Map<Continent, List<Country>> by lazy {
        countries.groupBy { it.continent }
    }

    fun countryByCode(code: String): Country? =
        countries.find { it.code == code }

    fun usStateByCode(code: String): SubRegion? =
        usStates.find { it.code == code }

    fun canadianProvinceByCode(code: String): SubRegion? =
        canadianProvinces.find { it.code == code }

    /** Get all sub-regions for a country code */
    fun statesFor(countryCode: String): List<SubRegion> = when (countryCode) {
        "US" -> usStates
        "CA" -> canadianProvinces
        "AU" -> australianStates
        "MX" -> mexicanStates
        "BR" -> brazilianStates
        "DE" -> germanStates
        "FR" -> frenchDepartments
        "ES" -> spanishCommunities
        "IT" -> italianProvinces
        "NL" -> dutchProvinces
        "BE" -> belgianProvinces
        "GB" -> ukCouncilAreas
        "RU" -> russianFederalSubjects
        "AR" -> argentineProvinces
        else -> emptyList()
    }

    /** Get the RegionType for a country's subdivisions */
    fun regionTypeForCountry(countryCode: String): RegionType? = when (countryCode) {
        "US" -> RegionType.US_STATE
        "CA" -> RegionType.CANADIAN_PROVINCE
        "AU" -> RegionType.AUSTRALIAN_STATE
        "MX" -> RegionType.MEXICAN_STATE
        "BR" -> RegionType.BRAZILIAN_STATE
        "DE" -> RegionType.GERMAN_STATE
        "FR" -> RegionType.FRENCH_REGION
        "ES" -> RegionType.SPANISH_COMMUNITY
        "IT" -> RegionType.ITALIAN_REGION
        "NL" -> RegionType.DUTCH_PROVINCE
        "BE" -> RegionType.BELGIAN_PROVINCE
        "GB" -> RegionType.UK_COUNTRY
        "RU" -> RegionType.RUSSIAN_FEDERAL_SUBJECT
        "AR" -> RegionType.ARGENTINE_PROVINCE
        else -> null
    }

    /** Flag emoji for a country code */
    fun flagEmoji(countryCode: String): String {
        if (countryCode.length != 2) return ""
        val first = Character.toChars(0x1F1E6 + (countryCode[0].uppercaseChar() - 'A'))
        val second = Character.toChars(0x1F1E6 + (countryCode[1].uppercaseChar() - 'A'))
        return String(first) + String(second)
    }

    /** Countries with state-level tracking */
    val countriesWithStates: List<Country> by lazy {
        countries.filter { it.hasStates }
    }

    /** Continent stats data for offline calculations */
    data class ContinentStatData(
        val name: String,
        val emoji: String,
        val total: Int,
        val codes: Set<String>
    )

    val continentStatData: List<ContinentStatData> = listOf(
        ContinentStatData("Europe", "\uD83C\uDFF0", 44, setOf("AL","AD","AT","BY","BE","BA","BG","HR","CZ","DK","EE","FI","FR","DE","GR","HU","IS","IE","IT","LV","LI","LT","LU","MT","MD","MC","ME","NL","MK","NO","PL","PT","RO","RU","SM","RS","SK","SI","ES","SE","CH","UA","GB","VA")),
        ContinentStatData("Asia", "\uD83C\uDF0F", 49, setOf("AF","AM","AZ","BH","BD","BT","BN","KH","CN","CY","GE","IN","ID","IR","IQ","IL","JP","JO","KZ","KW","KG","LA","LB","MY","MV","MN","MM","NP","KP","OM","PK","PS","PH","QA","SA","SG","KR","LK","SY","TW","TJ","TH","TL","TR","TM","AE","UZ","VN","YE")),
        ContinentStatData("Africa", "\uD83C\uDF0D", 54, setOf("DZ","AO","BJ","BW","BF","BI","CV","CM","CF","TD","KM","CG","CD","CI","DJ","EG","GQ","ER","SZ","ET","GA","GM","GH","GN","GW","KE","LS","LR","LY","MG","MW","ML","MR","MU","MA","MZ","NA","NE","NG","RW","ST","SN","SC","SL","SO","ZA","SS","SD","TZ","TG","TN","UG","ZM","ZW")),
        ContinentStatData("North America", "\uD83D\uDDFD", 23, setOf("AG","BS","BB","BZ","CA","CR","CU","DM","DO","SV","GD","GT","HT","HN","JM","MX","NI","PA","KN","LC","VC","TT","US")),
        ContinentStatData("South America", "\uD83C\uDF34", 12, setOf("AR","BO","BR","CL","CO","EC","GY","PY","PE","SR","UY","VE")),
        ContinentStatData("Oceania", "\uD83C\uDFDD\uFE0F", 14, setOf("AU","FJ","KI","MH","FM","NR","NZ","PW","PG","WS","SB","TO","TV","VU"))
    )
}
